security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        sil12\VitrineBundle\Entity\Client: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        users:
            entity: { class: sil12VitrineBundle:Client, property: mail }

    firewalls:
        vitrine_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /auth
                check_path: /auth_check
            logout:
                path: /logout
                target: /accueil


    access_control:
        - { path: ^/backoffice, roles: ROLE_ADMIN }
        - { path: ^/panier/validate, roles: ROLE_USER }