<?php

namespace sil12\VitrineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderhatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderhatRepository extends EntityRepository
{
	/*public function findBoughtWith() {



		return $this->getEntityManager()
					->createQuery('SELECT p FROM sil12VitrineBundle:Orderhat p ORDER BY p.name ASC')
					->getResult();
	}*/
}
