sil12\VitrineBundle\Entity\Client:
    type: entity
    id:
        id:
            type: integer
            nullable: false
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 100
        mail:
            type: string
            length: 100
        password:
            type: string
            length: 100
    oneToMany:
        orderline:
            targetEntity: Orderhat
            mappedBy: orderhat