sil12\VitrineBundle\Entity\Orderhat:
  type: entity
  repositoryClass: sil12\VitrineBundle\Entity\OrderhatRepository
  fields:
    id:
      id: true
      type: integer
      nullable: false
      generator:
        strategy: AUTO
    order_date:
        type: datetime
    validated:
        type: boolean
  oneToMany:
    orderline:
      targetEntity: sil12\VitrineBundle\Entity\OrderLine
      mappedBy: orderhat
  manyToOne:
    client:
      targetEntity: sil12\VitrineBundle\Entity\Client
      inversedBy: orderhat
      joinColumn:
        client_id:
          referencedColumName: id