sil12\VitrineBundle\Entity\Product:
  type: entity
  repositoryClass: sil12\VitrineBundle\Entity\ProductRepository
  fields:
    id:
      id: true
      type: integer
      nullable: false
      generator:
        strategy: AUTO
    name:
      type: string
      length: 100
    price:
      type: decimal
      precision: 10
      scale: 2
    description:
      type: text
    label:
      type: string
      length: 100
    stock:
      type: integer
  oneToMany:
    orderline:
      targetEntity: sil12\VitrineBundle\Entity\OrderLine
      mappedBy: product
  manyToOne:
    category:
      targetEntity: sil12\VitrineBundle\Entity\Category
      inversedBy: product
      joinColumns:
        category_id:
          referencedColumnName: id
  manyToMany:
    promotions:
      targetEntity: Promotion
      inversedBy: products
      joinTable:
        name: products_promotions
        joinColumns:
          product_id:
            referencedColumnName: id
        inverseJoinColumns:
          promotion_id:
            referencedColumnName: id