sil12_vitrine_accueil:
    pattern:  /accueil
    defaults: { _controller: sil12VitrineBundle:Default:index }

sil12_vitrine_mentions:
    pattern: /mentions
    defaults: { _controller: sil12VitrineBundle:Default:mentions }

sil12_vitrine_catalogue:
    pattern: /catalogue
    defaults: { _controller: sil12VitrineBundle:Default:catalogue }

sil12_vitrine_articlesParCategorie:
    pattern: /category/{id}
    defaults: { _controller: sil12VitrineBundle:Default:articlesParCategorie }

sil12_vitrine_filteredArticlesParCategorie:
    pattern: /categoryFiltered
    defaults: { _controller: sil12VitrineBundle:Default:filteredArticlesParCategorie }
    requirements: { _method: post }

sil12_vitrine_chapeau:
    pattern: /chapeau/{id}/{nb}
    defaults: { _controller: sil12VitrineBundle:Default:chapeau, nb: 1 }



sil12_vitrine_myorders_show:
    pattern:  /myorders_show/{id}
    defaults: { _controller: "sil12VitrineBundle:Default:myOrdersShow" }

sil12_vitrine_myorders:
    pattern:  /myorders
    defaults: { _controller: "sil12VitrineBundle:Default:myOrders" }

sil12_vitrine_shareProduct:
    pattern: /share
    defaults: { _controller: sil12VitrineBundle:Default:shareProduct }
    requirements: { _method: post }

sil12_vitrine_contenuPanier:
    pattern: /panier
    defaults: { _controller: sil12VitrineBundle:Panier:contenuPanier}

sil12_vitrine_addProduct:
    pattern: /panier/add/{id}/{qte}
    defaults: { _controller: sil12VitrineBundle:Panier:addProduct, id: null, qte: 1 }

sil12_vitrine_deleteProduct:
    pattern: /panier/del/{id}/{qte}
    defaults: { _controller: sil12VitrineBundle:Panier:deleteProduct, id: null, qte: 1 }



sil12_vitrine_removeProduct:
    pattern: /panier/{id}
    defaults: { _controller: sil12VitrineBundle:Panier:removeProduct, id: null }

sil12_vitrine_validationPanier:
    pattern: /paniervalidate
    defaults: { _controller: sil12VitrineBundle:Panier:validationPanier }



sil12_vitrine_backoffice:
    pattern: /backoffice
    defaults: { _controller: sil12VitrineBundle:BackOffice:index, id: null, type: null, nb: 1 }





sil12VitrineBundle_product:
    resource: "@sil12VitrineBundle/Resources/config/routing/product.yml"
    prefix:   /backoffice/product

sil12VitrineBundle_category:
    resource: "@sil12VitrineBundle/Resources/config/routing/category.yml"
    prefix:   /backoffice/category

sil12VitrineBundle_client:
    resource: "@sil12VitrineBundle/Resources/config/routing/client.yml"
    prefix:   /backoffice/client

sil12VitrineBundle_orderhat:
    resource: "@sil12VitrineBundle/Resources/config/routing/orderhat.yml"
    prefix:   /backoffice/orderhat


sil12_vitrine_auth:
    pattern:  /auth
    defaults: { _controller: sil12VitrineBundle:Client:auth }

auth_check:
    pattern: /auth_check

logout:
    pattern: /logout


sil12VitrineBundle_promotion:
        resource: "@sil12VitrineBundle/Resources/config/routing/promotion.yml"
        prefix:   /promotion
